export enum OrderStatus {
  PENDIENTE_CONFIRMACION = 'PENDIENTE_CONFIRMACION',
  PENDIENTE = 'PENDIENTE',
  EN_COCINA = 'EN_COCINA',
  LISTO = 'LISTO',
  ENTREGADO = 'ENTREGADO',
  CANCELADO = 'CANCELADO',
}
